add feature anonymize initiatives
OpenSourcePolitics/decidim-sen pull request #76
Opened 2022-12-15 15:46 UTC by eliegaboriau

#### :tophat: Description
*Please describe your pull request.*
This PR adds the possibility to anonymize every initiatives created before 3 years ago.
It also launch automatically every day this feature.
Anonymizing here references to attributing the petition to a deleted user.

#### :pushpin: Related Issues
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=aed08bbf2b2e46e581cd0bfc1aefb1bb&p=ad766b7fb5014903b93557e10876a3c4&pm=c)

#### Testing
*Describe the best way to test or validate your PR.*

Example:
* Modify in database an initiative creation date
* Launch the task
* See the petition showing a deleted user as the author

#### Tasks
- [x] Add specs
- [x] Add note about overrides in OVERLOADS.md

2022-12-15 18:20 UTC, armandfardeau requested changes
Hey, thanks for your contribution, lets have a meeting to discuss changes.

2022-12-16 06:53 UTC, eliegaboriau commented on app/services/decidim/check_anonymizable_initiatives_service.rb
> +    end
I'm trying to create a deleted user in the organization only when it's necessary, and to fetch him when he already existed.

2023-01-11 09:18 UTC, paulinebessoles commented
Thank you for the PR @eliegaboriau @armandfardeau! I have one feedback, after running the task, I see that on the initiative show, two authors are displayed: the "deleted author" (anonymized) and the original author. 

<img width="1239" alt="Capture d’écran 2023-01-11 à 10 15 05" src="https://user-images.githubusercontent.com/52420208/211766586-b41af5df-c77d-40df-9c06-59e138060bd8.png">

Could you fix this? I'm available for a call if needed 😀

2023-01-11 10:43 UTC, eliegaboriau commented
It should be okay now @paulinebessoles

2023-01-11 10:46 UTC, paulinebessoles commented on app/views/decidim/initiatives/initiatives/_author.html.erb
> +        <% byebug %>
Could you delete the byebug here? 😁

2023-01-11 10:49 UTC, eliegaboriau commented on app/views/decidim/initiatives/initiatives/_author.html.erb
> +        <% byebug %>
oups

2023-01-11 10:56 UTC, paulinebessoles approved these changes

2023-01-12 16:00 UTC, merged